# Pipeline for azure-search-openai-demo

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    #!/bin/bash

    echo "Update apt repositories"
    sudo apt update -y

    echo "Install azd"
    curl -fsSL https://aka.ms/install-azd.sh | bash

    echo "Install Python3"
    sudo apt install python3 -y
    sudo apt install python-is-python3 -y

    echo "Install git"
    sudo apt install git -y

    echo "Install nodejs"
    sudo apt install nodejs -y
    sudo apt install npm -y  
  displayName: 'Install dependencies'

- script: |
    #!/bin/bash

    export BROWSER="/usr/bin/firefox"
    export DISPLAY="$(grep nameserver /etc/resolv.conf | sed 's/nameserver //'):0"

    echo "Login to Azure"
    azd auth login --use-device-code
  displayName: 'Set up project'
