# Pipeline for azure-search-openai-demo

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: AZURE_OPENAI_SERVICE
  value: ahc-prod-openai-svc

- name: AZURE_OPENAI_RESOURCE_GROUP
  value: ahc-prod-openai-rg

- name: AZURE_FORMRECOGNIZER_SERVICE
  value: ahc-prod-openai-form

- name: AZURE_FORMRECOGNIZER_RESOURCE_GROUP
  value: ahc-prod-openai-rg

- name: AZURE_SEARCH_SERVICE
  value: ahc-prod-openai-search

- name: AZURE_SEARCH_SERVICE_RESOURCE_GROUP
  value: ahc-prod-openai-rg

- name: AZURE_STORAGE_ACCOUNT
  value: ahc-prod-openai-storage

- name: AZURE_STORAGE_RESOURCE_GROUP
  value: ahc-prod-openai-rg

steps:
- script: |
    #!/bin/bash

    echo "Update apt repositories"
    sudo apt update -y

    echo "Install azd"
    curl -fsSL https://aka.ms/install-azd.sh | bash

    echo "Install Python3"
    sudo apt install python3 -y
    sudo apt install python-is-python3 -y

    echo "Install git"
    sudo apt install git -y

    echo "Install nodejs"
    sudo apt install nodejs -y
    sudo apt install npm -y  
  displayName: 'Install dependencies'

- script: |
    #!/bin/bash

    echo "Login to Azure"
    export BROWSER="/usr/bin/firefox"
    yes "" | azd auth login --use-device-code

    echo "Initialize Project"
     yes "Overwrite with versions from template" | azd init --subscription ec79f31d-9166-44f3-ae41-b45024f7492a -l eastus -t azure-search-openai-demo -e prod
  displayName: 'Initialize project'

- script: |
    #!/bin/bash

    echo "Setup project env variables"
    azd env set AZURE_OPENAI_SERVICE ${{ variables.AZURE_OPENAI_SERVICE }}
    azd env set AZURE_OPENAI_RESOURCE_GROUP ${{ variables.AZURE_OPENAI_RESOURCE_GROUP }}
    azd env set AZURE_FORMRECOGNIZER_SERVICE ${{ variables.AZURE_FORMRECOGNIZER_SERVICE }}
    azd env set AZURE_FORMRECOGNIZER_RESOURCE_GROUP ${{ variables.AZURE_FORMRECOGNIZER_RESOURCE_GROUP }}
    azd env set AZURE_SEARCH_SERVICE ${{ variables.AZURE_SEARCH_SERVICE }}
    azd env set AZURE_SEARCH_SERVICE_RESOURCE_GROUP ${{ variables.AZURE_SEARCH_SERVICE_RESOURCE_GROUP }}
    azd env set AZURE_STORAGE_ACCOUNT ${{ variables.AZURE_STORAGE_ACCOUNT }}
    azd env set AZURE_STORAGE_RESOURCE_GROUP ${{ variables.AZURE_STORAGE_RESOURCE_GROUP }}

    echo "Deploy Project"
    yes "East US" | azd up
  displayName: 'Deploy Project'
