# Pipeline for azure-search-openai-demo

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    #!/bin/bash

    echo "Update apt repositories"
    sudo apt update -y

    echo "Install azd"
    curl -fsSL https://aka.ms/install-azd.sh | bash

    echo "Install Python3"
    sudo apt install python3 -y
    sudo apt install python-is-python3 -y

    echo "Install git"
    sudo apt install git -y

    echo "Install nodejs"
    sudo apt install nodejs -y
    sudo apt install npm -y  
  displayName: 'Install dependencies'

- script: |
    #!/bin/bash

    echo "Login to Azure"
    export BROWSER="/usr/bin/firefox"
    yes "" | azd auth login --use-device-code

    echo "Initialize Project"
     yes "Overwrite with versions from template" | azd init --subscription ec79f31d-9166-44f3-ae41-b45024f7492a -l eastus -t azure-search-openai-demo -e prod
  displayName: 'Initialize project'

- script: |
    #!/bin/bash

    echo "Deploy Project"
    azd up
  displayName: 'Deploy Project'
